In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4])
type(arr1)

numpy.ndarray

In [5]:
arr2=np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr3=np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr4=np.arange(5)
arr4

array([0, 1, 2, 3, 4])

In [9]:
arr5=np.arange(5,15)
arr5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr6=np.arange(5,15,2)
arr6

array([ 5,  7,  9, 11, 13])

In [12]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
arr8=np.arange(24).reshape(6,4)
arr8


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
arr8[3]

array([12, 13, 14, 15])

In [19]:
arr8[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
arr8[-1]

array([20, 21, 22, 23])

In [21]:
arr8[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
arr8[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
arr8[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [24]:
arr8[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [27]:
arr9=np.array([1,2,3,4,5,6])
arr10=np.array([4,5,6,7,8,9])
arr9-arr10

array([-3, -3, -3, -3, -3, -3])

In [28]:
arr9.dot(arr10)

154

In [29]:
arr9.min()

1

In [30]:
arr9.max()

6

In [33]:
arr11=np.arange(30).reshape(5,6)
arr11

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
arr11.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [37]:
arr11.max(axis=0)

array([24, 25, 26, 27, 28, 29])

In [36]:
arr11.min(axis=1)

array([ 0,  6, 12, 18, 24])

In [38]:
arr11.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [42]:
arr12=np.arange(6,12).reshape(3,2)
arr13=np.arange(12,18).reshape(3,2)
arr13

array([[12, 13],
       [14, 15],
       [16, 17]])

In [48]:
np.random.seed(200)
np.random.uniform(20.30)


2.010697442762762

In [50]:
np.random.uniform(1,100,10).reshape(2,5)

array([[98.61672363, 92.40340396, 31.06563808, 84.76424554, 13.00097488],
       [78.77205226, 25.80000042, 10.50694131, 94.40561266, 82.77896457]])